### ISSUE TITLE
error: specified package `bam-builder v0.1.3` has no binaries

### ISSUE THREAD

**Issue by brainstorm** [sstadick/bam-builder#1]
```
% cargo install bam-builder
    Updating crates.io index
  Downloaded bam-builder v0.1.3
  Downloaded 1 crate (14.1 KB) in 1.86s
error: specified package `bam-builder v0.1.3` has no binaries
```

Expectation/UX: a ready-to-go binary to create BAM files of arbitrary size... perhaps based on `/dev/random` modulo {ACGT} bases :)

**Comment by brainstorm** [comment]
... and a quickstart on the `README.md` based on one of the examples: paste this cmdline and get a 50MB random BAM file ;)

**Comment by brainstorm** [comment]
I totally get that this is a library and that `% git clone... && cargo build && cargo run --example ex1` does the job, but if you publish it on `crates.io`, there should be **at least** one bin that does something interesting... not to mention avoiding the `cargo install` error, IMHO ;)

Kudos for this crate, btw, love it ;)

**Comment by sstadick** [comment]
Ha! Well thanks for trying to install it! I hadn't even considered a binary.

I had to go and make sure I was in good company though:

```bash
❯ cargo install rust-htslib    
    Updating crates.io index
  Downloaded rust-htslib v0.36.0
  Downloaded 1 crate (164.8 KB) in 0.64s
error: specified package `rust-htslib v0.36.0` has no binaries
```

But a binary that generates some a random BAM does seem useful...

**Comment by brainstorm** [comment]
Haha, touché, well played XD

I'm not sure which "default binaries" would htslib have though, your lib seems more purpose-built for testing that's why, but I do get your point ;)
